name: Checkmarx One Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkmarx AST Github Action
        uses: Checkmarx/ast-github-action@2.0.23
        with:
          base_uri: https://ind.iam.checkmarx.net/
          cx_tenant: ama-partners
          cx_client_id: ME123_CxOne_Client
          cx_client_secret: BQHNkrH9QleEGjTuwdAv8hoJNrFFO6Pm
          project_name: palanivel_WebGoat
          branch: master
          github_token: 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
          additional_params: --report-format sarif --output-path cx_result.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with: 
          sarif_file: cx_result.sarif
